name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy lúc 00:00 UTC mỗi ngày
  push:
    branches:
      - main  # Thay đổi nếu nhánh chính của bạn là nhánh khác

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build HTML
        run: echo "Building HTML..."  # Thay thế nếu có bước build cụ thể

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_HTML }}
          publish_dir: .  # Thư mục chứa các file cần triển khai (ở đây là root)