name: Daily Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy lúc 00:00 UTC mỗi ngày

jobs:
  run-daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install HTMLHint
        run: |
          npm install -g htmlhint

      - name: Validate HTML
        run: htmlhint index.html